# justfile - Developer task runner for autom8y-asana
# Conventions match autom8y monorepo (Justfile)
set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false
set export := true

default:
    @just --list

# === Repository Path Bootstrap ===

# Register this repository's path in ~/.config/autom8y/paths.env
[group('setup')]
bootstrap-paths:
    #!/usr/bin/env bash
    set -euo pipefail
    PATHS_FILE="${HOME}/.config/autom8y/paths.env"
    REPO_PATH=$(git rev-parse --show-toplevel)
    VAR_NAME="AUTOM8Y_ASANA_PATH"
    echo "=== Registering ${VAR_NAME} ==="
    mkdir -p "$(dirname "$PATHS_FILE")"
    if [ ! -f "$PATHS_FILE" ]; then
        printf '%s\n' "# autom8y Repository Paths" "# ========================" "# Auto-generated by: just bootstrap-paths" "# Edit manually if repos are moved." "" > "$PATHS_FILE"
    fi
    if grep -q "^export ${VAR_NAME}=" "$PATHS_FILE" 2>/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^export ${VAR_NAME}=.*|export ${VAR_NAME}=\"${REPO_PATH}\"|" "$PATHS_FILE"
        else
            sed -i "s|^export ${VAR_NAME}=.*|export ${VAR_NAME}=\"${REPO_PATH}\"|" "$PATHS_FILE"
        fi
        echo "Updated: ${VAR_NAME}=${REPO_PATH}"
    else
        echo "export ${VAR_NAME}=\"${REPO_PATH}\"" >> "$PATHS_FILE"
        echo "Added: ${VAR_NAME}=${REPO_PATH}"
    fi
    echo ""
    echo "Paths configuration: $PATHS_FILE"

# Check all configured repository paths (diagnostic command)
[group('setup')]
check-paths:
    #!/usr/bin/env bash
    set -euo pipefail
    PATHS_FILE="${HOME}/.config/autom8y/paths.env"
    echo "=== Repository Path Configuration ==="
    echo "Config file: $PATHS_FILE"
    echo ""
    if [ ! -f "$PATHS_FILE" ]; then
        echo "WARNING: $PATHS_FILE does not exist"
        echo ""
        echo "Run 'just bootstrap-paths' in each repository to configure."
        exit 0
    fi
    set -a && source "$PATHS_FILE" && set +a
    echo "Configured paths:"
    grep '^export AUTOM8Y_' "$PATHS_FILE" | while read -r line; do
        VAR_NAME=$(echo "$line" | sed 's/^export \([^=]*\)=.*/\1/')
        VAR_VALUE="${!VAR_NAME:-}"
        if [ -n "$VAR_VALUE" ] && [ -d "$VAR_VALUE" ]; then
            echo "  $VAR_NAME: $VAR_VALUE (valid)"
        elif [ -n "$VAR_VALUE" ]; then
            echo "  $VAR_NAME: $VAR_VALUE (NOT FOUND)"
        fi
    done

# === Code Quality ===

# Sync dependencies
[group('dev')]
sync:
    uv sync

# Format code
[group('quality')]
fmt:
    uv run ruff format .

# Format check (CI)
[group('quality')]
fmt-check:
    uv run ruff format . --check

# Lint and auto-fix. Note: does NOT run ruff format — use `just fmt` for that.
[group('quality')]
lint:
    uv run ruff check . --fix

# Type check
[group('quality')]
typecheck:
    uv run mypy src/ --strict

# Drift-guard: fail on any NEW unused noqa in src/ (non-fixing; does not auto-delete)
[group('quality')]
lint-noqa-drift:
    uv run ruff check src/ --extend-select RUF100

# === Testing ===

# Run tests
[group('test')]
test *args:
    uv run pytest {{args}}

# Run tests with coverage report
[group('test')]
test-cov:
    uv run pytest --cov=autom8_asana --cov-report=html --cov-report=term

# Run fast tests only (no slow, integration, or benchmarks)
[group('test')]
test-fast *args:
    uv run pytest tests/ -m "not slow and not integration and not benchmark" {{args}}

# Run slow tests only
[group('test')]
test-slow *args:
    uv run pytest tests/ -m "slow" {{args}}

# Run integration tests (requires ASANA_PAT)
[group('test')]
test-integration *args:
    uv run pytest tests/ -m "integration" {{args}}

# Run benchmarks
[group('test')]
test-bench *args:
    uv run pytest tests/ -m "benchmark" {{args}}

# Run AST fitness guards — fast, no-deps, safe for pre-push and scoped runs.
# Catches: FROZEN-4 concurrency invariants + unsanctioned to_thread detection.
# Run before pushing: it is fast (7 tests, no xdist) and catches concurrency-offload
# regressions that otherwise only surface in full-shard CI (CLASS-1b scoped-run-miss).
[group('test')]
fitness:
    uv run pytest tests/unit/dataframes/test_concurrency_invariants_guard.py \
        -p no:xdist -o addopts="" -v --no-header

# Uses the ROOT project env (--project ..): mcp tests need only httpx/pydantic/
# pytest/pytest-asyncio (fastmcp test self-skips; autom8y-core faked — README).
# Canary POLARITY: pytest rc==1 on canary/ == broken fixture correctly tripped
# == GREEN receipt; rc==0 (no teeth) or rc==5 (vacuous) FAIL this recipe.
# Run the mcp/ island suite + teeth canary (CI parity: test.yml mcp-island job)
[group('test')]
test-mcp:
    #!/usr/bin/env bash
    set -euo pipefail
    cd mcp
    uv run --project .. python -m pytest tests -q
    set +e
    uv run --project .. python -m pytest canary -q --tb=line
    rc=$?
    set -e
    if [ "$rc" -eq 1 ]; then
        echo "Canary correctly tripped (rc=1) — mcp-island gate has teeth."
    else
        echo "Canary polarity violation: rc=${rc} (expected exactly 1)." >&2
        exit 1
    fi

# === Combined Checks ===

# Full CI-equivalent check
[group('quality')]
check: fmt lint typecheck lint-noqa-drift test

# === OpenAPI ===

# Regenerate committed OpenAPI spec
[group('docs')]
spec-gen:
    uv run python scripts/generate_openapi.py

# Verify OpenAPI spec matches source (CI drift check)
[group('docs')]
spec-check:
    uv run python scripts/generate_openapi.py --check

# === Development Server ===

# Start API development server with hot reload
[group('dev')]
serve-api port="8000":
    uv run uvicorn autom8_asana.api.main:create_app --factory --reload --port {{port}}

# Check API health endpoint
[group('dev')]
health port="8000":
    #!/usr/bin/env bash
    set -euo pipefail
    URL="http://localhost:{{port}}/health"
    echo "Checking: $URL"
    RESPONSE=$(curl -s -w "\n%{http_code}" "$URL")
    STATUS=$(echo "$RESPONSE" | tail -1)
    BODY=$(echo "$RESPONSE" | head -n -1)
    if [ "$STATUS" -eq 200 ]; then
        echo "Status: $STATUS OK"
        echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
    else
        echo "ERROR: Health check failed (status $STATUS)"
        echo "$BODY"
        exit 1
    fi

# Warm DataFrame cache by building and persisting to S3
[group('dev')]
warm-cache:
    uv run python scripts/warm_cache.py

# === Docker ===

# Build Docker image
[group('docker')]
docker-build tag="latest":
    docker build -t autom8y-asana:{{tag}} .

# Run Docker container
[group('docker')]
docker-run port="8000" tag="latest":
    docker run --rm -p {{port}}:8000 \
        -e ASANA_PAT="${ASANA_PAT:-}" \
        -e LOG_LEVEL="${LOG_LEVEL:-INFO}" \
        autom8y-asana:{{tag}}

# Build and run Docker container
[group('docker')]
docker-serve port="8000" tag="latest": (docker-build tag) (docker-run port tag)

# === Cleanup ===

# Clean build artifacts
[group('cleanup')]
[confirm("This will delete build artifacts. Continue?")]
clean:
    rm -rf .coverage htmlcov/ .pytest_cache/ .mypy_cache/ .ruff_cache/
    find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

# ============================================
# Runbook Support Commands
# ============================================
# Minimal commands designed for one-liner use in Atuin Desktop runbooks.
# Environment auto-loaded from: ~/.config/autom8y/envs/autom8y-asana/runbook.env

# Setup runbook environment (creates ~/.config/autom8y/envs/autom8y-asana/runbook.env)
[group('setup')]
setup-env:
    #!/usr/bin/env bash
    set -euo pipefail

    TEMPLATE="runbooks/atuin/environments/local.env.example"
    TARGET_DIR="${HOME}/.config/autom8y/envs/autom8y-asana"
    TARGET_FILE="${TARGET_DIR}/runbook.env"

    echo "=== autom8y-asana Onboarding Setup ==="

    if [ ! -f "$TEMPLATE" ]; then
        echo "ERROR: Template not found: $TEMPLATE"
        exit 1
    fi

    mkdir -p "$TARGET_DIR"

    if [ -f "$TARGET_FILE" ]; then
        BACKUP="${TARGET_FILE}.backup.$(date +%Y%m%d%H%M%S)"
        echo "Backing up existing env to $BACKUP"
        cp "$TARGET_FILE" "$BACKUP"
    fi

    echo "Copying template..."
    cp "$TEMPLATE" "$TARGET_FILE"

    echo ""
    echo "Environment file created: $TARGET_FILE"
    echo ""
    echo "Next: Add your ASANA_PAT (Personal Access Token from Asana)"

# Check required environment variables for runbooks (names and presence states only)
[group('setup')]
check-env:
    #!/usr/bin/env bash
    set -euo pipefail

    # Auto-load runbook environment
    ENV_FILE="${HOME}/.config/autom8y/envs/autom8y-asana/runbook.env"
    [ -f "$ENV_FILE" ] && set -a && source "$ENV_FILE" && set +a

    echo "=== autom8y-asana Environment Check ==="
    MISSING=""

    # One state per NAME, keyed on its companion A8_CRED_VERSION_<NAME>: set-ness and a
    # byte-exact "0" comparison only. The companion is never parsed and its expiry is never
    # read; no value, length, suffix, prefix or hash is printed. See .know/env-loader.md.
    cred_state() {
        local name="$1" comp="A8_CRED_VERSION_$1"
        if [ -z "${!name:-}" ]; then
            echo "${name}: missing"
            return 1
        fi
        if [ -n "${!comp+x}" ] && [ "${!comp}" != "0" ]; then
            echo "${name}: set (substrate-marked)"
            echo "  note: may be inherited or expired; decide per .know/env-loader.md"
            if [ -e .env/local ]; then
                echo "  note: .env/local also exists (a legacy copy); see .know/env-loader.md"
            fi
        elif [ -n "${!comp+x}" ]; then
            echo "${name}: set (not substrate: withheld or shadowed)"
        else
            echo "${name}: set (not substrate: no companion)"
        fi
    }

    # Required variables
    cred_state ASANA_PAT || MISSING="$MISSING ASANA_PAT"
    # Reported, not required by this check
    cred_state ASANA_WORKSPACE_GID || true

    if [ -n "$MISSING" ]; then
        echo "ERROR: Missing required variables:$MISSING"
        echo ""
        echo "Fix: Run 'just setup-env' then add your ASANA_PAT"
        exit 1
    fi

    echo "API_HOST: ${API_HOST:-0.0.0.0}"
    echo "API_PORT: ${API_PORT:-8000}"
    echo "LOG_LEVEL: ${LOG_LEVEL:-INFO}"
    echo "ENV_FILE: $ENV_FILE"
    echo ""
    echo "Environment OK"

# LEGACY (pre-substrate): fetch the service secrets into .env/local; refuses only when its own env carries A8_CRED_VERSION_ASANA_PAT other than 0 (OW-3)
[group('legacy')]
fetch-secrets:
    #!/usr/bin/env bash
    set -euo pipefail
    # Guard first, before any AWS call: refuse when the companion A8_CRED_VERSION_ASANA_PAT
    # is SET and not byte-exactly "0" (the empty value included). It is compared to "0"
    # only: never parsed, never its expiry, never a credential value.
    if [ -n "${A8_CRED_VERSION_ASANA_PAT+x}" ] && [ "$A8_CRED_VERSION_ASANA_PAT" != "0" ]; then
        echo "fetch-secrets: REFUSED: A8_CRED_VERSION_ASANA_PAT is set in this process env (served here, or inherited). operator: to decide for this tree run: env -u ASANA_PAT -u A8_CRED_VERSION_ASANA_PAT direnv exec . printenv A8_CRED_VERSION_ASANA_PAT; read the result per .know/env-loader.md (a blocked .envrc reads the same as unset). Declared at .a8-credentials." >&2
        exit 3
    fi
    if [ -n "${A8_CRED_VERSION_ASANA_PAT+x}" ]; then
        echo "fetch-secrets: NOTE: A8_CRED_VERSION_ASANA_PAT is 0 (withheld or shadowed); .env/local is a fallback copy, silent once served; retire it per .know/env-loader.md"
    fi
    # Write: the temp file first (mode 600), removed on any exit. Each fetch appends straight
    # into it, so values never pass through a shell variable. mv last replaces any prior
    # .env/local, so the result is mode 600 even when a prior copy was wider.
    umask 077
    mkdir -p .env
    tmp=$(mktemp .env/local.XXXXXX)
    trap 'rm -f "$tmp"' EXIT
    echo "Fetching autom8y-asana secrets from AWS Secrets Manager..."
    printf '# Local development secrets (gitignored)\n# Generated by: just fetch-secrets (%s)\n' "$(date +%Y-%m-%d)" >> "$tmp"
    { printf '%s=' ASANA_PAT; aws secretsmanager get-secret-value --secret-id "autom8y/asana/asana-pat" --query SecretString --output text; } >> "$tmp" \
        || { echo "ERROR: Failed to fetch ASANA_PAT"; exit 1; }
    # Per-name write (OW-12): skip a name whose OWN companion A8_CRED_VERSION_<NAME> is set
    # and not byte-exactly "0", by the guard's own two checks. Only the GID can be skipped:
    # the guard above already refused a served PAT. `skipped` holds a NAME, never a value.
    skipped=""
    if [ -n "${A8_CRED_VERSION_ASANA_WORKSPACE_GID+x}" ] && [ "$A8_CRED_VERSION_ASANA_WORKSPACE_GID" != "0" ]; then
        skipped="ASANA_WORKSPACE_GID"
    else
        { printf '%s=' ASANA_WORKSPACE_GID; aws secretsmanager get-secret-value --secret-id "autom8y/asana/asana-workspace-gid" --query SecretString --output text; } >> "$tmp" \
            || { echo "ERROR: Failed to fetch ASANA_WORKSPACE_GID"; exit 1; }
    fi
    mv -f "$tmp" .env/local
    if [ -n "$skipped" ]; then
        echo "Written: .env/local (1 name; skipped, companion set and not 0: $skipped)"
    else
        echo "Written: .env/local (2 names)"
    fi
    echo "LEGACY: .env/local is the pre-substrate path. This repo declares at .a8-credentials. This recipe refuses only when its own env carries A8_CRED_VERSION_ASANA_PAT other than 0 (OW-3); a shell without the direnv hook, or any withhold or shadowed, lets it write. When it writes, it skips each name whose own A8_CRED_VERSION_<NAME> is set and not 0 (OW-12). It retires with main's .env/local at A3(d) (OW-4). See .know/env-loader.md."

# === Workflow Invocation ===

# Invoke a workflow (direct mode)
[group('runbook')]
invoke workflow_id *args:
    uv run python scripts/invoke_workflow.py {{workflow_id}} {{args}}
