# justfile - Developer task runner for autom8y-asana
# Conventions match autom8y monorepo (Justfile)
set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false
set export := true

default:
    @just --list

# === Repository Path Bootstrap ===

# Register this repository's path in ~/.config/autom8y/paths.env
bootstrap-paths:
    #!/usr/bin/env bash
    set -euo pipefail
    PATHS_FILE="${HOME}/.config/autom8y/paths.env"
    REPO_PATH=$(git rev-parse --show-toplevel)
    VAR_NAME="AUTOM8Y_ASANA_PATH"
    echo "=== Registering ${VAR_NAME} ==="
    mkdir -p "$(dirname "$PATHS_FILE")"
    if [ ! -f "$PATHS_FILE" ]; then
        printf '%s\n' "# autom8y Repository Paths" "# ========================" "# Auto-generated by: just bootstrap-paths" "# Edit manually if repos are moved." "" > "$PATHS_FILE"
    fi
    if grep -q "^export ${VAR_NAME}=" "$PATHS_FILE" 2>/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^export ${VAR_NAME}=.*|export ${VAR_NAME}=\"${REPO_PATH}\"|" "$PATHS_FILE"
        else
            sed -i "s|^export ${VAR_NAME}=.*|export ${VAR_NAME}=\"${REPO_PATH}\"|" "$PATHS_FILE"
        fi
        echo "Updated: ${VAR_NAME}=${REPO_PATH}"
    else
        echo "export ${VAR_NAME}=\"${REPO_PATH}\"" >> "$PATHS_FILE"
        echo "Added: ${VAR_NAME}=${REPO_PATH}"
    fi
    echo ""
    echo "Paths configuration: $PATHS_FILE"

# Check all configured repository paths (diagnostic command)
check-paths:
    #!/usr/bin/env bash
    set -euo pipefail
    PATHS_FILE="${HOME}/.config/autom8y/paths.env"
    echo "=== Repository Path Configuration ==="
    echo "Config file: $PATHS_FILE"
    echo ""
    if [ ! -f "$PATHS_FILE" ]; then
        echo "WARNING: $PATHS_FILE does not exist"
        echo ""
        echo "Run 'just bootstrap-paths' in each repository to configure."
        exit 0
    fi
    set -a && source "$PATHS_FILE" && set +a
    echo "Configured paths:"
    grep '^export AUTOM8Y_' "$PATHS_FILE" | while read -r line; do
        VAR_NAME=$(echo "$line" | sed 's/^export \([^=]*\)=.*/\1/')
        VAR_VALUE="${!VAR_NAME:-}"
        if [ -n "$VAR_VALUE" ] && [ -d "$VAR_VALUE" ]; then
            echo "  $VAR_NAME: $VAR_VALUE (valid)"
        elif [ -n "$VAR_VALUE" ]; then
            echo "  $VAR_NAME: $VAR_VALUE (NOT FOUND)"
        fi
    done

# === Code Quality ===

# Sync dependencies
sync:
    uv sync

# Format code
fmt:
    uv run ruff format .

# Format check (CI)
fmt-check:
    uv run ruff format . --check

# Lint and auto-fix
lint:
    uv run ruff check . --fix

# Type check
typecheck:
    uv run mypy src/ --strict

# === Testing ===

# Run tests
test *args:
    uv run pytest {{args}}

# Run tests with coverage report
test-cov:
    uv run pytest --cov=autom8_asana --cov-report=html --cov-report=term

# Run fast tests only (no slow, integration, or benchmarks)
test-fast *args:
    uv run pytest tests/ -m "not slow and not integration and not benchmark" {{args}}

# Run slow tests only
test-slow *args:
    uv run pytest tests/ -m "slow" {{args}}

# Run integration tests (requires ASANA_PAT)
test-integration *args:
    uv run pytest tests/ -m "integration" {{args}}

# Run benchmarks
test-bench *args:
    uv run pytest tests/ -m "benchmark" {{args}}

# === Combined Checks ===

# Full CI-equivalent check
check: fmt lint typecheck test

# === Development Server ===

# Start API development server with hot reload
serve-api port="8000":
    uv run uvicorn autom8_asana.api.main:create_app --factory --reload --port {{port}}

# Check API health endpoint
health port="8000":
    #!/usr/bin/env bash
    set -euo pipefail
    URL="http://localhost:{{port}}/health"
    echo "Checking: $URL"
    RESPONSE=$(curl -s -w "\n%{http_code}" "$URL")
    STATUS=$(echo "$RESPONSE" | tail -1)
    BODY=$(echo "$RESPONSE" | head -n -1)
    if [ "$STATUS" -eq 200 ]; then
        echo "Status: $STATUS OK"
        echo "$BODY" | jq '.' 2>/dev/null || echo "$BODY"
    else
        echo "ERROR: Health check failed (status $STATUS)"
        echo "$BODY"
        exit 1
    fi

# Warm DataFrame cache by building and persisting to S3
warm-cache:
    uv run python scripts/warm_cache.py

# === Docker ===

# Build Docker image
docker-build tag="latest":
    docker build -t autom8y-asana:{{tag}} .

# Run Docker container
docker-run port="8000" tag="latest":
    docker run --rm -p {{port}}:8000 \
        -e ASANA_PAT="${ASANA_PAT:-}" \
        -e LOG_LEVEL="${LOG_LEVEL:-INFO}" \
        autom8y-asana:{{tag}}

# Build and run Docker container
docker-serve port="8000" tag="latest": (docker-build tag) (docker-run port tag)

# === Cleanup ===

# Clean build artifacts
clean:
    rm -rf .coverage htmlcov/ .pytest_cache/ .mypy_cache/ .ruff_cache/
    find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

# ============================================
# Runbook Support Commands
# ============================================
# Minimal commands designed for one-liner use in Atuin Desktop runbooks.
# Environment auto-loaded from: ~/.config/autom8y/envs/autom8y-asana/runbook.env

# Setup runbook environment (creates ~/.config/autom8y/envs/autom8y-asana/runbook.env)
setup-env:
    #!/usr/bin/env bash
    set -euo pipefail

    TEMPLATE="runbooks/atuin/environments/local.env.example"
    TARGET_DIR="${HOME}/.config/autom8y/envs/autom8y-asana"
    TARGET_FILE="${TARGET_DIR}/runbook.env"

    echo "=== autom8y-asana Onboarding Setup ==="

    if [ ! -f "$TEMPLATE" ]; then
        echo "ERROR: Template not found: $TEMPLATE"
        exit 1
    fi

    mkdir -p "$TARGET_DIR"

    if [ -f "$TARGET_FILE" ]; then
        BACKUP="${TARGET_FILE}.backup.$(date +%Y%m%d%H%M%S)"
        echo "Backing up existing env to $BACKUP"
        cp "$TARGET_FILE" "$BACKUP"
    fi

    echo "Copying template..."
    cp "$TEMPLATE" "$TARGET_FILE"

    echo ""
    echo "Environment file created: $TARGET_FILE"
    echo ""
    echo "Next: Add your ASANA_PAT (Personal Access Token from Asana)"

# Check required environment variables for runbooks
check-env:
    #!/usr/bin/env bash
    set -euo pipefail

    # Auto-load runbook environment
    ENV_FILE="${HOME}/.config/autom8y/envs/autom8y-asana/runbook.env"
    [ -f "$ENV_FILE" ] && set -a && source "$ENV_FILE" && set +a

    echo "=== autom8y-asana Environment Check ==="
    MISSING=""

    # Required variables
    [ -z "${ASANA_PAT:-}" ] && MISSING="$MISSING ASANA_PAT"

    if [ -n "$MISSING" ]; then
        echo "ERROR: Missing required variables:$MISSING"
        echo ""
        echo "Fix: Run 'just setup-env' then add your ASANA_PAT"
        exit 1
    fi

    echo "ASANA_PAT: ****${ASANA_PAT: -4}"
    echo "API_HOST: ${API_HOST:-0.0.0.0}"
    echo "API_PORT: ${API_PORT:-8000}"
    echo "LOG_LEVEL: ${LOG_LEVEL:-INFO}"
    echo "ENV_FILE: $ENV_FILE"
    echo ""
    echo "Environment OK"

# === Workflow Invocation ===

# Invoke a workflow (direct mode)
invoke workflow_id *args:
    uv run python scripts/invoke_workflow.py {{workflow_id}} {{args}}
