# .a8/autom8y/ecosystem.conf
# Ecosystem identity -- sourced by a8-devenv.sh
A8_ORG_NAME=autom8y
A8_AWS_ACCOUNT=696318035277
A8_AWS_REGION=us-east-1
A8_CODEARTIFACT_DOMAIN=autom8y
A8_ENV_CANONICAL="local staging production test"
A8_SSM_PREFIX=/autom8y
