name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: autom8y/autom8y-workflows/.github/workflows/security-dependency-review.yml@f5601acbe3905270dfcb9069854c78c0f940ad05
