name: Dependency Review

on:
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    uses: autom8y/autom8y-workflows/.github/workflows/security-dependency-review.yml@2b73d0b06823a1e816d4b40439c69476bb3c8b17
