name: Dependency Review

on:
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    uses: autom8y/autom8y-workflows/.github/workflows/security-dependency-review.yml@44b771e516a49a0d964782e4bbd0f0e39b2f97a1
