name: Secrets Scan (Gitleaks)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    uses: autom8y/autom8y-workflows/.github/workflows/security-gitleaks.yml@44b771e516a49a0d964782e4bbd0f0e39b2f97a1
