name: Secrets Scan (Gitleaks)

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    uses: autom8y/autom8y-workflows/.github/workflows/security-gitleaks.yml@f5601acbe3905270dfcb9069854c78c0f940ad05
