name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    uses: autom8y/autom8y/.github/workflows/satellite-ci-reusable.yml@2506cd146bbb8ba9326ef1ff1b9f58f6e8d5cb0c
    with:
      mypy_targets: 'src/autom8_asana'
      coverage_package: 'autom8_asana'
      coverage_threshold: 80
      test_parallel: true
      run_integration: ${{ github.event_name == 'push' }}
      test_env: 'ASANA_WORKSPACE_GID=1234567890123456'
    secrets: inherit
