name: TruffleHog Secrets Scan (Scheduled)

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  trufflehog:
    uses: autom8y/autom8y-workflows/.github/workflows/security-trufflehog.yml@2b73d0b06823a1e816d4b40439c69476bb3c8b17
