name: zizmor (Actions Security)

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'

jobs:
  zizmor:
    uses: autom8y/autom8y-workflows/.github/workflows/security-zizmor.yml@2b73d0b06823a1e816d4b40439c69476bb3c8b17
